### ISSUE TITLE
"Live" aspect of it not working. Refreshing page will show new messages but doesn't show new messages upon submission.

### ISSUE THREAD

**Issue by bfblackjack** [dazzz1er/confer#17]
Error from laravel log:

[2015-12-24 17:09:39] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Commands\Command' not found' in /home/crm/public_html/crmnew/vendor/djb/confer/src/Commands/MessageWasSent.php:11
Stack trace:
#0 {main}

**Comment by bfblackjack** [comment]
Using Laravel 5.1

**Comment by dazzz1er** [comment]
hi @bfblackjack confer was made for L5, I am yet to release a version for 5.1. This error is a direct result of the differences between the Laravel versions.

I haven't investigated but converting the confer commands to new L5.1 job style commands might be all that is needed to allow the package to work in L5.1.

**Comment by hallmichael** [comment]
Hi @bfblackjack @dazzz1er,

I investigated and converted the confer commands to Laravel 5.1's job style and it seemed to work. It should be noted though that there were a few more compatibility issues with 5.1 due to the required 'pusher/pusher-php-server' package. I think it was updated since Laravel 5 and confer requires it uses version 'dev-master', so to get it working with confer I had to manually set the options for a new pusher instance with the old method not the new options array.

I would be happy to look at changes required to get confer working with Laravel 5.2 as I would like to eventually implement it in 5.2 with an alternative theme.

Edit - I have everything working the last change is the method lists(), it is used frequently in confers code and `lists('example')` in Laravel 5.1 needs to be `lists('example')->all()`.

**Comment by dazzz1er** [comment]
@hallmichael great to hear it wasn't too bad for the conversion to 5.1, appreciate the work you've done there!

In future I think I could look at separating the code out in such a way that we can have custom themes easily implemented. Depending on the situation as well, I will likely create a new branch or repository for a version of confer which uses Redis + socket.js for pushing instead of pusher as it is much faster and has no third party service reliance.
