### ISSUE TITLE
bindShared not working?

### ISSUE THREAD

**Issue by striderxfossility** [dazzz1er/confer#45]
"Call to undefined method Illuminate\Foundation\Application::bindShared()"

I use laravelcollective/html.

What is the problem?

**Comment by LarryBarker** [comment]
I think it's something to do with the version of Laravel we're using because I'm having the same problem. I'm on 5.5 and can't get past registering the confer service provider 👎 

Update: Did a quick search on google, and found out it has to do with Laravel deprecating the bindShared method in favor of using the 'singleton' method.

Look here to get started: #https://github.com/laracasts/flash/issues/55

But this example show's what you want:
https://github.com/laracasts/flash/pull/53/commits/e1928bf4c1b14b7b373348bdcdf0c83cb2017e6f

In ConferServiceProvider.php register() method change::
```
$this->app->bindShared('push', function($app) {
```
to
```
$this->app->singleton('push', function($app) {
```

**Comment by striderxfossility** [comment]
Fixed

**Comment by LarryBarker** [comment]
@striderxfossility Was it my suggestion?

> I think it's something to do with the version of Laravel we're using because I'm having the same problem. I'm on 5.5 and can't get past registering the confer service provider 👎
> 
> Update: Did a quick search on google, and found out it has to do with Laravel deprecating the bindShared method in favor of using the 'singleton' method.
> 
> Look here to get started: #[laracasts/flash#55](https://github.com/laracasts/flash/issues/55)
> 
> But this example show's what you want:
> [laracasts/flash@e1928bf](https://github.com/laracasts/flash/commit/e1928bf4c1b14b7b373348bdcdf0c83cb2017e6f)
> 
> In ConferServiceProvider.php register() method change::
> 
> ```
> $this->app->bindShared('push', function($app) {
> ```
> to
> 
> ```
> $this->app->singleton('push', function($app) {
> ```

**Comment by striderxfossility** [comment]
Greetings,

No i have still bindshared, because it is in Vendor, and i dont change anything in there, when i update it will be overwritten.

i forgot wat my fix was but i guessed it was: You should remove this outdated package - "illuminate/html": "^5.0" in composer.json
